apiVersion: apps/v1

kind: Deployment

metadata:

  name: uat-deployment

  labels:

    app: uat

spec:

  replicas: 4

  selector:

    matchLabels:

      app: uat

  template:

    metadata:

      labels:

        app: uat

    spec:

      containers:

      - name: uat

        image: docker.io/tenzilabs/tenzibiz:inv.1.0

        ports:

        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: uat-service
spec:
  type: NodePort
  selector:
    app: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
