apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  labels:
    app: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: docker.io/tenzilabs/tenzibiz:inv.1.2
        ports:
        - containerPort: 80
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: server22-secret
              key: DBUSER
        - name: DBUSERPASSWORD
          valueFrom:
            secretKeyRef:
              name: server22-secret
              key: DBUSERPASSWORD
        - name: DBNAME
          valueFrom:
            secretKeyRef:
              name: server22-secret
              key: DBNAME
        - name:  DBSERVER
          valueFrom:
            configMapKeyRef:
              name: server22-config
              key: DBSERVER

---

apiVersion: v1
kind: Service
metadata:
  name: webapi-service
spec:
  type: NodePort
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100